{
 "title": "Myapp Dashboard Nginx",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Nginx Latency Quantile 0.5",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, (sum by (le)(rate(nginx_ingress_controller_request_duration_seconds_bucket[1m]))))"
    }
   ]
  },
  {
   "title": "Nginx Latency Quantile 0.95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, (sum by (le)(rate(nginx_ingress_controller_request_duration_seconds_bucket[1m]))))"
    }
   ]
  },
  {
   "title": "Nginx Latency Quantile 0.99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, (sum by (le)(rate(nginx_ingress_controller_request_duration_seconds_bucket[1m]))))"
    }
   ]
  },
  {
   "title": "Nginx Latency Quantile 1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "(sum by (le)(rate(nginx_ingress_controller_request_duration_seconds_count[1m])))"
    }
   ]
  },
  {
   "title": "Nginx RPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (status)(rate(nginx_ingress_controller_request_duration_seconds_count[1m]))"
    }
   ]
  },
  {
   "title": "Nginx 5+ Errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum by (status)(increase(nginx_ingress_controller_request_duration_seconds_count{status=~\"5.+\"}[1m]))"
    }
   ]
  }
 ]
}