{
 "title": "Myapp Dashboard 1",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Quantile 0.5",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, (sum by (le, uri, method)(rate(http_server_requests_seconds_bucket{uri=~\"/user.+\"}[1m]))))"
    }
   ]
  },
  {
   "title": "Quantile 0.95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, (sum by (le, uri, method)(rate(http_server_requests_seconds_bucket{uri=~\"/user.+\"}[1m]))))"
    }
   ]
  },
  {
   "title": "Quantile 0.99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, (sum by (le, uri, method)(rate(http_server_requests_seconds_bucket{uri=~\"/user.+\"}[1m]))))"
    }
   ]
  },
  {
   "title": "Quantile 1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "(sum by (le, uri, method)(rate(http_server_requests_seconds_count{uri=~\"/user.+\"}[1m])))"
    }
   ]
  },
  {
   "title": "RPS by uri/method",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (uri, method) (rate(http_server_requests_seconds_count{uri=~\"/user.+\"}[1m]))"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum by (status)(increase(http_server_requests_seconds_count{status=~\"5.+\"}[1m]))"
    }
   ]
  }
 ]
}