apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.app.configmapName }}
data:
  APP_DB_HOST: {{ .Values.postgresql.fullnameOverride }}
  APP_DB_NAME: {{ .Values.postgresql.postgresqlDatabase }}
  APP_DB_PORT: {{ .Values.db.port | quote }}
  APP_PORT: {{ .Values.app.portNumber | quote }}
  APP_DB_USERNAME: {{ .Values.postgresql.postgresqlUsername }}
  JAVA_OPTS: -Xms128m -Xmx256m