apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.migration.configmapName }}
data:
  DB_HOST: {{ .Values.postgresql.fullnameOverride }}
  DB_NAME: {{ .Values.postgresql.postgresqlDatabase }}
  DB_PORT: {{ .Values.postgresql.service.port | quote }}
  MIGRATION_DB_USER: {{ .Values.postgresql.postgresqlUsername}}